sudo: required
services:
  - docker

before_install:
  - docker build -t shafik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shafik/react-test npm test -- --coverage

after_success:
  - docker build -t shafik/complex-client ./client
  - docker build -t shafik/complex-nginx ./nginx
  - docker build -t shafik/complex-server ./server
  - docker build -t shafik/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  # Take those images and push them to docker hub
  - docker push shafik/complex-client
  - docker push shafik/complex-nginx
  - docker push shafik/complex-server
  - docker push shafik/complex-worker
# Heroku
#deploy:
 # provider: heroku
 # api_key:
  #  secure: "$heruko_api"
  #on:
   # branch: master
#
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-1-306476627547
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
